version: '3'
services:
  componentapp:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - REACT_APP_WEATHER_SERVICE_URL=http://localhost:80
  weatherservice:
    build:
      context: ./WeatherService
    ports:
      - 80:80 
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=AutomationDemo;User=sa;Password=YourStrongPassword123;MultipleActiveResultSets=true
    depends_on:
      - db
    volumes:
      - ./init-data.sql:/docker-entrypoint-initdb.d/init-data.sql
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123
      - MSSQL_PID=Developer
    command: /bin/bash -c "sleep 15 && /opt/mssql/bin/sqlservr"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -U sa -P YourStrongPassword123 -Q "SELECT 1" || exit 1
    volumes:
      - weather-data:/var/opt/mssql/data
volumes:
  weather-data:
    external: true

